### ISSUE TITLE
BNG still allows rules with dangling bonds

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RuleWorld/bionetgen#125]
```
We've agreed for quite a while that rules with dangling bonds should not be 
allowed in BNG. The BNGParser used by RuleBender flags rules with dangling 
bonds and displays an error. However, BNG itself still allows them. At some 
point we should fix this. Attached is a simple model containing a rule with a 
dangling bond. Ideally, this model would generate an error. However, in the 
current version of BNG (v2.2.5) it runs fine. 
```

Original issue reported on code.google.com by `lh64@cornell.edu` on 28 Jun 2014 at 12:59

Attachments:
- [dangling.bngl](https://storage.googleapis.com/google-code-attachments/bionetgen/issue-125/comment-0/dangling.bngl)

**Comment by jrfaeder** [comment]
BNG 2.3.1 returns the following:

BioNetGen version 2.3.1
Reading from file /Users/faeder/Dropbox/RuleBender-workspace/BNGIssues/issue_125.bngl (level 0)
Read 4 parameters.
Read 3 molecule types.
Read 2 species.
ERROR: SpeciesGraph::updateEdges(): dangling edge not allowed in species graph!
  at line 21
ABORT: Reaction rule list could not be read because of errors.
