### ISSUE TITLE
Characters in rule names

### ISSUE THREAD

**Issue by jjtapia** [RuleWorld/bionetgen#133]
Currently the default naming of rules includes the usage of non alphanumeric symbols. One example of this is the automatic naming of a reversible rule, which gets labeled as

*rulename*(reverse) 

This can be seen in the generated *.net file.

On the same vein, it would seem that the characters allowed in a rule name are not well defined. This makes static analysis that makes use of rule names more cumbersome than necessary as these characters require special handling.

The proposal is to restrict this automatic naming along with the set of allowed symbols to only include alphanumeric characters and the underscore symbol.

**Comment by lh64** [comment]
Joe Vigil and I made some progress in this direction last summer. The code is in the 'jvigil' branch. I haven't merged it because it hasn't been extensively tested but it probably makes sense to do it for the 2.2.6-stable release. I'll look into it.

Leonard

**Comment by johnsekar** [comment]
I have identified the lines in the code where changes need to be made and
it's a pretty simple fix. But, it breaks all the validations which use a
complete diff between files. So, if we're interested in redoing the
validations for 2.2.6, I can go ahead and make the changes.

- John

On Mar 19, 2015 5:07 PM, "Leonard Harris" <notifications@github.com> wrote:
>
> Joe Vigil and I made some progress in this direction last summer. The
code is in the 'jvigil' branch. I haven't merged it because it hasn't been
extensively tested but it probably makes sense to do it for the
2.2.6-stable release. I'll look into it.
>
> Leonard
>
>
> > On Mar 19, 2015, at 2:58 PM, Jose Juan Tapia <notifications@github.com>
wrote:
> >
> > Currently the default naming of rules includes the usage of non
alphanumeric symbols. A particular case of this is the automatic naming of
a reversible rule, which gets automatically labeled as
> >
> > (reverse) This can be seen in the generated *.net file.
> >
> > On the same vein, it would seem that the characters allowed in a rule
name are not well defined. This makes static analysis that makes use of
rule name more cumbersome than necessary as these characters require
special handling.
> >
> > The proposal is to restrict this automatic naming along with the set of
allowed symbols to only include alphanumeric characters and the underscore
symbol.

**Comment by jjtapia** [comment]
Can we mark this as closed then?

**Comment by lh64** [comment]
Yeah, I'm closing it now.
