### ISSUE TITLE
Moving sbmlparser to a separate repo

### ISSUE THREAD

**Issue by jjtapia** [RuleWorld/bionetgen#155]
So I was thinking on moving the atomizer project to its own repo withing the RuleWorld flag. For the time being I've created a repo with all the necessary files@ https://github.com/RuleWorld/SBMLparser

The reason for this are multiple:
- Building bionetgen from source now requires the user to install the sbmlparser dependencies if he wishes to pass all the tests
- Having sbmlparser in its own repo would allow me to include a more extensive set of tests for sbmlparser (specifically i want to add a bunch of stuff in the sbml validation suite) without bloating the current bionetgen validation process
- we have a precedent for this in nfsim
- basic validation tests can be left for validate_examples.pl if it detects the presence of an sbmlTranslator binary like it does for nfsim.
- the work we have done compilation and testing wise on different platforms would not be lost since I would just be porting it over to the new repo.

The downsides I've identified are the following:
- Like nfsim, if a user wishes to build bionetgen from source he would need to get the atomizer code independently and place the binary manually in the bin directory.
- The building and distribution prepartion process would also require extra steps.

Any thoughts on this?

**Comment by msneddon** [comment]
You might want to consider using git submodules, which allows you to split and organize things into focused, specific repos, but still allows you to explicitly set dependencies (based on a specific commit) across repos.  I find them very useful for situations like this, and I would actually suggest we do this with nfsim as well.

In the test scripts (or perhaps in a new installer/config script) it should be straightforward to do a quick check to ensure the submodules are pulled and up-to-date and that the necessary things are built and copied to the right directories.  Ideally users who want to build everything from source could then just run a test/install script rather than attempting to build each component manually and having to copy things around by hand.

**Comment by jjtapia** [comment]
This would indeed address most of the issues I identified. Thanks for the tip Michael, I'll look into this.
