### ISSUE TITLE
BioNetGen tries to continue old aborted simulations

### ISSUE THREAD

**Issue by rhclark** [RuleWorld/bionetgen#186]
Rulebender seems to have started initializing continuing simulations from ones before (initializing them from the endpoint of previous simulations), even when I tell it not to. For example, have a look at the attached bngl file.
[eModel_test.txt](https://github.com/RuleWorld/bionetgen/files/1188105/eModel_test.txt)

**Comment by lh64** [comment]
This is not a bug. The 'continue' command tells BNG whether or not to append the output (CDAT and/or GDAT) from the current run to that of the previous run. This is independent of whether the initial concentrations for the current run are the same as the final concentrations of the previous run. By default, BNG will start a simulation from the final state of a previous simulation. To prevent this, one should use the 'resetConcentrations' command.

The commands for continuation simulations are a bit confusing. It's possible to reset the concentrations using 'resetConcentrations' and append the output using 'continue=>1', even though this makes little sense to do. Also, while 't_start' is set to the final time of the previous simulation, 't_end' is not automatically scaled relative to that time (e.g., if the first simulation finishes at t=100 and 't_end' is set to 10 in the second simulation, an error will result rather than 't_end' getting set to 110). Some of these issues are enumerated here: https://github.com/RuleWorld/bionetgen/issues/29
